language: generic
branches:
  except:
   - appveyor
notifications:
  email:
    recipients:
      - slam6d-commits@lists.sourceforge.net
    on_success: change
    on_failure: always
env: # needed for allow_failures
matrix:
  include:
    - os: osx
      before_cache:
        - brew cleanup
      cache:
        directories:
        - $HOME/Library/Caches/Homebrew
script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./travismacosbuild.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ./travisdockerbuild.sh $DERIV $DIST $CC; fi
