build:
 verbosity: detailed
# we can only support a single visual studio version because the cache is too
# small to fit multiple vcpkg caches
image: Visual Studio 2017
platform: x64
branches:
  except:
   - travis
environment:
  matrix:
   - PLATFORM: msvc
#     # APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#   - PLATFORM: cygwin
#   - PLATFORM: mingw
# connect via rdp using:
#    $ xfreerdp /d:domain /u:appveyor /p:'password' /cert-ignore /v:ipaddr:port
#init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
for:
 - matrix:
     only:
      - PLATFORM: cygwin
   build_script:
    - cmd: "%APPVEYOR_BUILD_FOLDER%\\windows\\cygwin.cmd"
 - matrix:
     only:
      - PLATFORM: mingw
   build_script:
    - cmd: "%APPVEYOR_BUILD_FOLDER%\\windows\\mingw.cmd"
   # pacman cache would exceed 1,048,576,000 bytes
   #cache:
   # - C:\msys64\var\cache\pacman\pkg\
 - matrix:
     only:
      - PLATFORM: msvc
   build_script:
    - cmd: C:\Python36-x64\python.exe %APPVEYOR_BUILD_FOLDER%\windows\timeout.py 4800 %APPVEYOR_BUILD_FOLDER%\windows\build.cmd %APPVEYOR_BUILD_FOLDER% C:\slam6d
   cache:
    - c:\slam6d\3rdparty\vcpkg\installed\ -> appveyor.yml
    - c:\slam6d\3rdparty\vcpkg\scripts\ -> appveyor.yml
    - c:\slam6d\3rdparty\vcpkg\triplets\ -> appveyor.yml
    - c:\slam6d\3rdparty\vcpkg\ports\ -> appveyor.yml
    - c:\slam6d\3rdparty\vcpkg\vcpkg.exe -> appveyor.yml
    - c:\slam6d\3rdparty\vcpkg\.vcpkg-root -> appveyor.yml
#cache: c:\tools\vcpkg\installed\ -> appveyor.yml, windows/build.cmd
notifications:
  - provider: Email
    to:
     - slam6d-commits@lists.sourceforge.net
    on_build_failure: true
    on_build_status_changed: true
